export const siteConfig = {
  name: 'Shubham Mane',
  title: 'AWS Cloud Engineer | DevOps Engineer',
  description: 'AWS Cloud Engineer & DevOps Engineer portfolio - cloud infrastructure, IaC, and automation',
  url: 'https://shubhu.io',
  basePath: '/',
  author: {
    name: 'Shubham Mane',
    email: 'shubhamane10@gmail.com',
    username: 'shubhu-io',
    avatar: 'https://avatars.githubusercontent.com/u/54975871?v=4',
    bio: 'Entry-level AWS Cloud/DevOps Engineer with hands-on experience designing, provisioning, and automating cloud infrastructure on AWS',
    location: 'Chhatrapati Sambhaji Nagar, Maharashtra',
    available: true,
  },
  social: {
    github: 'https://github.com/shubhu-io',
    linkedin: 'https://www.linkedin.com/in/shubham-mane-dev/',
    twitter: 'https://x.com/shubh__m_',
    reddit: 'https://www.reddit.com/user/shubhu_m/',
    pinterest: 'https://in.pinterest.com/shubhvibessss/',
    tumblr: 'https://www.tumblr.com/blog/shubhustuff',
    instagram: 'https://www.instagram.com/shubh.now/',
    substack: 'https://substack.com/@shubhvibes',
    discord: 'https://discordapp.com/users/568683246502674434',
    medium: 'https://medium.com/@shubhxplore',
    email: 'shubhamane10@gmail.com',
    leetcode: 'https://leetcode.com/u/INl1aAlk0A/',
    hackerrank: 'https://www.hackerrank.com/shubhamane10',
    devto: 'https://dev.to/shubhxplore',
    portfolio: 'https://shubhu-io.github.io/Shubham-Mane/',
    resume: '/Shubham_Mane_Resume.pdf',
  },
  github: {
    username: 'shubhu-io',
    token: import.meta.env.VITE_GITHUB_TOKEN || '',
  },
  theme: {
    defaultDark: true,
  },
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Blog', href: '/blog' },
  ],
}
